sudo: false
language: node_js
node_js:
  - 'node'
cache:
  npm: false
script:
  - npm test -- --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
service_name: travis-pro
repo_token: c77d0b1eaefb7b94b1063813a408905d46c081ef
